<?php

namespace Gemboot\Notifications;

use NotificationChannels\Telegram\TelegramMessage;
use Illuminate\Notifications\Notification;

class Telegram extends Notification
{
    public function via($notifiable)
    {
        return ["telegram"];
    }

    public function toTelegram($notifiable)
    {
        if (app('config')->get('gemboot.notifications.enable')) {
            $telegram_user_id = app('config')->get('gemboot.notifications.telegram.chat_id');
            $content = $notifiable->content;

            return TelegramMessage::create()
                // Optional recipient user id.
                ->to($telegram_user_id)
                // Markdown supported.
                ->content($content)
                ->line("")
                ->line("_generated by gemboot-lara_");
        } else {
            return null;
        }
    }
}
